import { buildCallGraph, reachable } from './callGraph.ts'
import {
  CACHE_IDLE_TIMEOUT_MS,
  CHUNK_SIZE,
  MAX_CACHE_ENTRIES,
  MAX_CONCURRENT,
} from '../../src/constants.ts'

const SOURCE_FILES = [
  'src/chunkCache.ts',
  'src/CachedFilehandle.ts',
  'src/RemoteFileWithRangeCache.ts',
]

const KINDS = {
  plain: 'fillcolor="#f6f8fa" color="#57606a"',
  shared: 'fillcolor="#fff8c5" color="#9a6700"',
  io: 'fillcolor="#dafbe1" color="#1a7f37"',
  caller: 'fillcolor="#ddf4ff" color="#0969da"',
}

/**
 * The steps worth drawing. Everything else the code calls is collapsed through:
 * an edge here means one of these reaches another without passing a third, so a
 * step that is renamed, dropped or rewired changes the diagram rather than
 * outliving it. Only the wording of `detail` is written by hand, and its numbers
 * come from constants.ts.
 */
const NODES: { key: string; kind: keyof typeof KINDS; detail?: string }[] = [
  { key: 'RemoteFileWithRangeCache#read', kind: 'plain', detail: 'key = url' },
  {
    key: 'CachedFilehandle#read',
    kind: 'plain',
    detail: 'key = whatever names the bytes',
  },
  { key: 'chunkCache.ts#getCachedRange', kind: 'plain' },
  {
    key: 'chunkCache.ts#planRead',
    kind: 'plain',
    detail: `one pass over a ${CHUNK_SIZE / 1024} KiB grid`,
  },
  {
    key: 'chunkCache.ts#getCached',
    kind: 'shared',
    detail: 'a hit, moved to newest',
  },
  {
    key: 'chunkCache.ts#joinChunk',
    kind: 'shared',
    detail: 'another read is fetching it',
  },
  {
    key: 'chunkCache.ts#fetchRun',
    kind: 'shared',
    detail: 'one request per run of misses',
  },
  {
    key: 'chunkCache.ts#limitConcurrency',
    kind: 'shared',
    detail: `≤ ${MAX_CONCURRENT} in flight per origin`,
  },
  { key: 'doFetch', kind: 'plain', detail: 'whatever the entry point passed' },
  { key: 'chunkCache.ts#publishChunk', kind: 'shared' },
  {
    key: 'chunkCache.ts#putCached',
    kind: 'shared',
    detail: `${MAX_CACHE_ENTRIES} chunks, LRU, ${CACHE_IDLE_TIMEOUT_MS / 60_000} min idle`,
  },
  { key: 'chunkCache.ts#assembleRange', kind: 'plain' },
]

const ENTRY_POINTS = new Set([
  'RemoteFileWithRangeCache#read',
  'CachedFilehandle#read',
])

function shortName(key: string) {
  return key.includes('#') ? key.slice(key.indexOf('#') + 1) : key
}

function id(key: string) {
  return key.replace(/[^A-Za-z0-9]/g, '_')
}

function label(key: string, detail: string | undefined) {
  const name = key.startsWith('chunkCache.ts#')
    ? shortName(key)
    : key.replace('#', '.')
  return detail === undefined ? name : `${name}\\n${detail}`
}

export function buildArchitectureDot() {
  const graph = buildCallGraph(SOURCE_FILES)
  for (const { key } of NODES) {
    if (key !== 'doFetch' && !graph.defined.has(key)) {
      throw new Error(
        `${key} is in the diagram but no longer in the source — update NODES in scripts/diagrams/architecture.ts`,
      )
    }
  }
  const sources = [...(graph.calls.get('doFetch') ?? [])].sort()
  const nodes = [
    ...NODES,
    ...sources.map(key => ({ key, kind: 'io' as const, detail: undefined })),
  ]
  const keep = new Set(nodes.map(n => n.key))

  const lines = [
    '// Generated by scripts/diagrams/architecture.ts — do not edit.',
    '// Every node is a function in src/, every edge is a call the source makes,',
    '// and every number comes from src/constants.ts. Regenerate both this and',
    '// its SVG with: pnpm diagrams',
    'digraph architecture {',
    '  rankdir=TB',
    '  bgcolor="white"',
    '  nodesep=0.3',
    '  ranksep=0.36',
    '  node [shape=box style="filled,rounded" fontname="Helvetica" fontsize=10 margin="0.14,0.07"]',
    '  edge [color="#57606a" fontname="Helvetica" fontsize=9]',
    '',
    `  caller [label="a parser's read(length, position, { signal })" ${KINDS.caller}]`,
    '',
    '  subgraph cluster_entry {',
    '    label="the only part that knows what the source is"',
    '    labelloc="t" fontname="Helvetica" fontsize=9 fontcolor="#57606a"',
    '    color="#d0d7de" style="rounded" margin=9',
  ]
  for (const node of nodes.filter(n => ENTRY_POINTS.has(n.key))) {
    lines.push(
      `    ${id(node.key)} [label="${label(node.key, node.detail)}" ${KINDS[node.kind]}]`,
    )
  }
  lines.push('  }', '')
  for (const node of nodes.filter(n => !ENTRY_POINTS.has(n.key))) {
    lines.push(
      `  ${id(node.key)} [label="${label(node.key, node.detail)}" ${KINDS[node.kind]}]`,
    )
  }
  lines.push('', `  out [label="Uint8Array" ${KINDS.caller}]`, '')
  for (const key of ENTRY_POINTS) {
    lines.push(`  caller -> ${id(key)}`)
  }
  // A source is drawn as one of the things `doFetch` turns out to be, so that
  // is the only way into it. `limitConcurrency` calls whatever it is handed and
  // so reaches `fetchRange` directly as well — through `stat`'s size probe,
  // which is not this diagram's path.
  for (const from of nodes) {
    for (const to of reachable(graph, from.key, keep)) {
      if (!sources.includes(to) || from.key === 'doFetch') {
        lines.push(`  ${id(from.key)} -> ${id(to)}`)
      }
    }
  }
  lines.push(`  ${id('chunkCache.ts#assembleRange')} -> out`)
  // layout only: the bytes are cached before they are assembled, and saying so
  // puts assembly under the fetch it waits for rather than beside it
  lines.push(
    `  ${id('chunkCache.ts#putCached')} -> ${id('chunkCache.ts#assembleRange')} [style=invis]`,
  )
  lines.push(
    '',
    '  subgraph cluster_legend {',
    '    label="Legend"',
    '    labelloc="t" fontname="Helvetica" fontsize=10 fontcolor="#57606a"',
    '    color="#d0d7de" style="rounded" margin=9',
    '    node [shape=box style="filled,rounded" fontsize=9 margin="0.1,0.04"]',
    `    l1 [label="I/O" ${KINDS.io}]`,
    `    l2 [label="cached / shared" ${KINDS.shared}]`,
    `    l3 [label="caller's read" ${KINDS.caller}]`,
    '    { rank=same; l1; l2; l3 }',
    '    l1 -> l2 -> l3 [style=invis]',
    '  }',
    '  out -> l1 [style=invis]',
    '}',
    '',
  )
  return lines.join('\n')
}
