import { RemoteFileWithRangeCache } from '../../src/RemoteFileWithRangeCache.ts'
import { clearCache } from '../../src/chunkCache.ts'
import {
  CACHE_IDLE_TIMEOUT_MS,
  CHUNK_SIZE,
  MAX_CACHE_ENTRIES,
} from '../../src/constants.ts'

const URL_KEY = 'https://example.com/reads.bam'
const FILE_CHUNKS = 8
const POSITION = Math.round(CHUNK_SIZE * 2.3)
const LENGTH = Math.round(CHUNK_SIZE * 4.6)

interface Range {
  start: number
  end: number
}

/**
 * Run the read the diagram draws, and report what the cache actually did with
 * it: which chunks it served, which it joined, and the range headers it sent.
 * Nothing here decides any of that — the picture is whatever this observes.
 */
async function observeRead() {
  clearCache()
  const size = FILE_CHUNKS * CHUNK_SIZE
  const requests: Range[] = []
  const startChunk = Math.floor(POSITION / CHUNK_SIZE)
  const lastChunk = Math.floor((POSITION + LENGTH - 1) / CHUNK_SIZE)
  // one chunk of the read is left in flight by another reader, so the diagram
  // shows a chunk being joined as well as chunks being fetched
  const joined = lastChunk - 1
  let release: (() => void) | undefined

  const fetch = async (_url: string | URL | Request, init?: RequestInit) => {
    const header = new Headers(init?.headers).get('range')
    const match = header ? /bytes=(\d+)-(\d+)/.exec(header) : null
    if (!match) {
      throw new Error(`the diagram's read sent no range header: ${header}`)
    }
    const start = Number(match[1])
    const end = Math.min(Number(match[2]), size - 1)
    requests.push({ start, end })
    if (start === joined * CHUNK_SIZE) {
      await new Promise<void>(resolve => {
        release = resolve
      })
    }
    return new Response(new Uint8Array(end - start + 1), {
      status: 206,
      headers: { 'content-range': `bytes ${start}-${end}/${size}` },
    })
  }

  const file = new RemoteFileWithRangeCache(URL_KEY, { fetch })
  await file.read(CHUNK_SIZE, startChunk * CHUNK_SIZE)
  const cached = startChunk
  const other = file.read(1, joined * CHUNK_SIZE)

  const before = requests.length
  const read = file.read(LENGTH, POSITION)
  // planRead runs to completion before the first await, so every request this
  // read makes has already been recorded
  const runs = requests.slice(before)
  if (release === undefined) {
    throw new Error(`chunk ${joined} was meant to still be in flight`)
  }
  release()

  const bytes = await read
  await other
  if (bytes.length !== LENGTH) {
    throw new Error(`the read returned ${bytes.length} bytes, not ${LENGTH}`)
  }
  return { startChunk, lastChunk, cached, joined, runs }
}

const COLUMN = 110
const MARGIN = 60

function bytes(n: number) {
  return n.toLocaleString('en-US')
}

function kib(n: number) {
  return `${Math.round(n / 1024)} KiB`
}

export async function buildChunksSvg() {
  const { startChunk, lastChunk, cached, joined, runs } = await observeRead()
  const first = startChunk - 1
  const last = lastChunk + 1
  const width = MARGIN * 2 + (last - first + 1) * COLUMN
  const at = (position: number) =>
    Math.round((MARGIN + (position / CHUNK_SIZE - first) * COLUMN) * 10) / 10
  const column = (index: number) => at(index * CHUNK_SIZE)
  const centre = (index: number) => column(index) + COLUMN / 2

  const readStart = at(POSITION)
  const readEnd = at(POSITION + LENGTH)
  const parts: string[] = []
  const add = (...lines: string[]) => parts.push(...lines)

  add(
    `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="436" viewBox="0 0 ${width} 436"`,
    '     font-family="Helvetica, Arial, sans-serif" role="img"',
    `     aria-label="A read of ${bytes(LENGTH)} bytes at ${bytes(POSITION)} covering chunks ${startChunk} to ${lastChunk}, served as ${runs.length} range requests">`,
    '  <!-- Generated by scripts/diagrams/chunks.ts — do not edit. Every number here',
    '       was observed by running the real chunk cache. Regenerate: pnpm diagrams -->',
    `  <rect width="${width}" height="436" fill="white"/>`,
    '  <defs>',
    '    <marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">',
    '      <path d="M 0 0 L 10 5 L 0 10 z" fill="#57606a"/>',
    '    </marker>',
    '  </defs>',
    `  <text x="30" y="34" font-size="13" fill="#24292f">One read, on the ${kib(CHUNK_SIZE)} chunk grid</text>`,
    `  <text x="30" y="52" font-size="10.5" fill="#57606a">${bytes(LENGTH)} bytes at ${bytes(POSITION)} span ${lastChunk - startChunk + 1} chunks. One is cached and one is already being fetched, so ${runs.length} requests reach the network.</text>`,
  )

  add(
    `  <rect x="${readStart}" y="80" width="${readEnd - readStart}" height="20" rx="4" fill="#ddf4ff" stroke="#0969da"/>`,
    `  <text x="${(readStart + readEnd) / 2}" y="94" font-size="10" fill="#0969da" text-anchor="middle">read(length = ${bytes(LENGTH)}, position = ${bytes(POSITION)})</text>`,
    `  <line x1="${readStart}" y1="100" x2="${readStart}" y2="128" stroke="#0969da" stroke-dasharray="3 2"/>`,
    `  <line x1="${readEnd}" y1="100" x2="${readEnd}" y2="128" stroke="#0969da" stroke-dasharray="3 2"/>`,
  )

  for (let index = first; index <= last; index++) {
    const inRead = index >= startChunk && index <= lastChunk
    const isCached = index === cached
    const isJoined = index === joined
    const fill = isCached || isJoined ? '#fff8c5' : '#f6f8fa'
    const stroke = isCached || isJoined ? '#9a6700' : '#57606a'
    const dash = isJoined ? ' stroke-dasharray="4 3"' : ''
    add(
      `  <g${inRead ? '' : ' opacity="0.4"'}>`,
      `    <rect x="${column(index)}" y="128" width="${COLUMN}" height="46" fill="${fill}" stroke="${stroke}"${dash}/>`,
      `    <text x="${centre(index)}" y="149" font-size="10" fill="#24292f" text-anchor="middle">chunk ${index}</text>`,
      `    <text x="${centre(index)}" y="164" font-size="9" fill="#57606a" text-anchor="middle">${bytes(index * CHUNK_SIZE)}</text>`,
      '  </g>',
    )
    if (inRead) {
      const note = isCached
        ? ['cached — serve it']
        : isJoined
          ? ['in flight — join that', 'run, request nothing']
          : ['missing']
      note.forEach((line, offset) => {
        add(
          `  <text x="${centre(index)}" y="${190 + offset * 12}" font-size="9.5" fill="${isCached || isJoined ? '#9a6700' : '#57606a'}" text-anchor="middle">${line}</text>`,
        )
      })
    }
  }

  for (const run of runs) {
    const left = at(run.start)
    const right = at(run.end + 1)
    const middle = (left + right) / 2
    // wide enough for the header it is labelled with, whatever the run's width
    const boxWidth = Math.max(right - left, 210)
    const boxX = Math.min(
      Math.max(middle - boxWidth / 2, 30),
      width - 30 - boxWidth,
    )
    add(
      `  <path d="M ${left + 2} 216 v 8 h ${right - left - 4} v -8" fill="none" stroke="#57606a"/>`,
      `  <line x1="${middle}" y1="224" x2="${middle}" y2="252" stroke="#57606a" marker-end="url(#arrow)"/>`,
      `  <rect x="${boxX}" y="258" width="${boxWidth}" height="40" rx="4" fill="#dafbe1" stroke="#1a7f37"/>`,
      `  <text x="${boxX + boxWidth / 2}" y="274" font-size="10" fill="#24292f" text-anchor="middle">Range: bytes=${run.start}-${run.end}</text>`,
      `  <text x="${boxX + boxWidth / 2}" y="289" font-size="9" fill="#1a7f37" text-anchor="middle">one request, ${kib(run.end - run.start + 1)}</text>`,
      `  <line x1="${middle}" y1="298" x2="${middle}" y2="330" stroke="#57606a" marker-end="url(#arrow)"/>`,
    )
  }

  add(
    `  <rect x="${readStart}" y="336" width="${readEnd - readStart}" height="24" rx="4" fill="#ddf4ff" stroke="#0969da"/>`,
    `  <text x="${(readStart + readEnd) / 2}" y="352" font-size="10" fill="#0969da" text-anchor="middle">Uint8Array(${bytes(LENGTH)}) — each chunk copied in at (its start − ${bytes(POSITION)})</text>`,
    `  <line x1="30" y1="380" x2="${width - 30}" y2="380" stroke="#d0d7de"/>`,
    `  <text x="30" y="399" font-size="10.5" fill="#57606a">Chunks ${startChunk}–${lastChunk} are now cached, so the next read of any of these bytes issues nothing.</text>`,
    `  <text x="30" y="414" font-size="10.5" fill="#57606a">They are held until ${MAX_CACHE_ENTRIES} newer chunks push them out, or ${CACHE_IDLE_TIMEOUT_MS / 60_000} minutes pass with nothing touching them.</text>`,
    '</svg>',
    '',
  )
  return parts.join('\n')
}
