import { RemoteFileWithRangeCache } from '../../src/RemoteFileWithRangeCache.ts'
import { clearCache } from '../../src/chunkCache.ts'
import {
  CACHE_IDLE_TIMEOUT_MS,
  CHUNK_SIZE,
  MAX_CACHE_ENTRIES,
} from '../../src/constants.ts'

const URL_KEY = 'https://example.com/reads.bam'
const FILE_CHUNKS = 8
const POSITION = Math.round(CHUNK_SIZE * 2.3)
const LENGTH = Math.round(CHUNK_SIZE * 4.6)

interface Range {
  start: number
  end: number
}

/**
 * Run the read the diagram draws, and report what the cache actually did with
 * it: which chunks it served, which it joined, and the range headers it sent.
 * Nothing here decides any of that — the picture is whatever this observes.
 */
async function observeRead() {
  clearCache()
  const size = FILE_CHUNKS * CHUNK_SIZE
  const requests: Range[] = []
  const startChunk = Math.floor(POSITION / CHUNK_SIZE)
  const lastChunk = Math.floor((POSITION + LENGTH - 1) / CHUNK_SIZE)
  // one chunk of the read is left in flight by another reader, so the diagram
  // shows a chunk being joined as well as chunks being fetched
  const joined = lastChunk - 1
  let release: (() => void) | undefined

  const fetch = async (_url: string | URL | Request, init?: RequestInit) => {
    const header = new Headers(init?.headers).get('range')
    const match = header ? /bytes=(\d+)-(\d+)/.exec(header) : null
    if (!match) {
      throw new Error(`the diagram's read sent no range header: ${header}`)
    }
    const start = Number(match[1])
    const end = Math.min(Number(match[2]), size - 1)
    requests.push({ start, end })
    if (start === joined * CHUNK_SIZE) {
      await new Promise<void>(resolve => {
        release = resolve
      })
    }
    return new Response(new Uint8Array(end - start + 1), {
      status: 206,
      headers: { 'content-range': `bytes ${start}-${end}/${size}` },
    })
  }

  const file = new RemoteFileWithRangeCache(URL_KEY, { fetch })
  await file.read(CHUNK_SIZE, startChunk * CHUNK_SIZE)
  const cached = startChunk
  const other = file.read(1, joined * CHUNK_SIZE)

  const before = requests.length
  const read = file.read(LENGTH, POSITION)
  // planRead runs to completion before the first await, so every request this
  // read makes has already been recorded
  const runs = requests.slice(before)
  if (release === undefined) {
    throw new Error(`chunk ${joined} was meant to still be in flight`)
  }
  release()

  const bytes = await read
  await other
  if (bytes.length !== LENGTH) {
    throw new Error(`the read returned ${bytes.length} bytes, not ${LENGTH}`)
  }
  return { startChunk, lastChunk, cached, joined, runs }
}

const COLUMN = 116
const MARGIN = 40
const HEIGHT = 330

function bytes(n: number) {
  return n.toLocaleString('en-US')
}

function kib(n: number) {
  return `${Math.round(n / 1024)} KiB`
}

export async function buildChunksSvg() {
  const { startChunk, lastChunk, cached, joined, runs } = await observeRead()
  const covered = lastChunk - startChunk + 1
  const fetched = runs.reduce(
    (total, run) => total + (run.end + 1 - run.start) / CHUNK_SIZE,
    0,
  )
  const width = MARGIN * 2 + covered * COLUMN
  const at = (position: number) =>
    Math.round((MARGIN + (position / CHUNK_SIZE - startChunk) * COLUMN) * 10) /
    10
  const centre = (index: number) => at(index * CHUNK_SIZE) + COLUMN / 2

  const readStart = at(POSITION)
  const readEnd = at(POSITION + LENGTH)
  const parts: string[] = []
  const add = (...lines: string[]) => parts.push(...lines)

  add(
    `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${HEIGHT}" viewBox="0 0 ${width} ${HEIGHT}"`,
    '     font-family="Helvetica, Arial, sans-serif" role="img"',
    `     aria-label="A read of ${bytes(LENGTH)} bytes at ${bytes(POSITION)} covering chunks ${startChunk} to ${lastChunk}, served as ${runs.length} range requests">`,
    '  <!-- Generated by scripts/diagrams/chunks.ts — do not edit. Every number here',
    '       was observed by running the real chunk cache. Regenerate: pnpm diagrams -->',
    `  <rect width="${width}" height="${HEIGHT}" fill="white"/>`,
    '  <defs>',
    '    <marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">',
    '      <path d="M 0 0 L 10 5 L 0 10 z" fill="#57606a"/>',
    '    </marker>',
    '  </defs>',
    `  <text x="${MARGIN}" y="30" font-size="13" fill="#24292f">One read, on the ${kib(CHUNK_SIZE)} chunk grid</text>`,
    `  <text x="${MARGIN}" y="49" font-size="10.5" fill="#57606a">It covers ${covered} chunks. Chunk ${cached} is cached and chunk ${joined} is already being fetched, so the ${fetched} chunks it still needs become ${runs.length} requests.</text>`,
    `  <rect x="${readStart}" y="72" width="${readEnd - readStart}" height="20" rx="4" fill="#ddf4ff" stroke="#0969da"/>`,
    `  <text x="${(readStart + readEnd) / 2}" y="86" font-size="10" fill="#0969da" text-anchor="middle">read(${bytes(LENGTH)} bytes at ${bytes(POSITION)})</text>`,
    `  <line x1="${readStart}" y1="92" x2="${readStart}" y2="112" stroke="#0969da" stroke-dasharray="3 2"/>`,
    `  <line x1="${readEnd}" y1="92" x2="${readEnd}" y2="112" stroke="#0969da" stroke-dasharray="3 2"/>`,
  )

  for (let index = startChunk; index <= lastChunk; index++) {
    const held = index === cached || index === joined
    const state =
      index === cached ? 'cached' : index === joined ? 'in flight' : 'missing'
    add(
      `  <rect x="${at(index * CHUNK_SIZE)}" y="112" width="${COLUMN}" height="44" fill="${held ? '#fff8c5' : '#f6f8fa'}" stroke="${held ? '#9a6700' : '#57606a'}"${index === joined ? ' stroke-dasharray="4 3"' : ''}/>`,
      `  <text x="${centre(index)}" y="132" font-size="10" fill="#24292f" text-anchor="middle">chunk ${index}</text>`,
      `  <text x="${centre(index)}" y="146" font-size="9" fill="${held ? '#9a6700' : '#57606a'}" text-anchor="middle">${state}</text>`,
    )
  }

  for (const run of runs) {
    const left = at(run.start)
    const right = at(run.end + 1)
    const middle = (left + right) / 2
    // wide enough for the header it is labelled with, whatever the run's width
    const boxWidth = Math.max(right - left, 176)
    const boxX = Math.min(
      Math.max(middle - boxWidth / 2, 10),
      width - 10 - boxWidth,
    )
    add(
      `  <path d="M ${left + 2} 168 v 8 h ${right - left - 4} v -8" fill="none" stroke="#57606a"/>`,
      `  <line x1="${middle}" y1="176" x2="${middle}" y2="196" stroke="#57606a" marker-end="url(#arrow)"/>`,
      `  <rect x="${boxX}" y="202" width="${boxWidth}" height="26" rx="4" fill="#dafbe1" stroke="#1a7f37"/>`,
      `  <text x="${boxX + boxWidth / 2}" y="219" font-size="10" fill="#24292f" text-anchor="middle">Range: bytes=${run.start}-${run.end}</text>`,
      `  <line x1="${middle}" y1="228" x2="${middle}" y2="252" stroke="#57606a" marker-end="url(#arrow)"/>`,
    )
  }

  add(
    `  <rect x="${readStart}" y="258" width="${readEnd - readStart}" height="22" rx="4" fill="#ddf4ff" stroke="#0969da"/>`,
    `  <text x="${(readStart + readEnd) / 2}" y="273" font-size="10" fill="#0969da" text-anchor="middle">Uint8Array(${bytes(LENGTH)})</text>`,
    `  <text x="${MARGIN}" y="310" font-size="10.5" fill="#57606a">Chunks ${startChunk}–${lastChunk} are cached now, until ${MAX_CACHE_ENTRIES} newer chunks push them out or ${CACHE_IDLE_TIMEOUT_MS / 60_000} minutes pass with nothing touching them.</text>`,
    '</svg>',
    '',
  )
  return parts.join('\n')
}
